services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: time_manager_dev
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  backend:
    build: ./backend
    restart: always
    ports:
      - 4005:4000
    environment:
      - DATABASE_URL=ecto://postgres_user:postgres_password@db:5432/time_manager_dev
      - SECRET_KEY_BASE=UVEpCoG1NUs/A+Gylf6624lJnLb7G2ozGxX79VejR34KyOo+i3b1M0kT4HtOgonR
      - ECTO_IPV6=false
      - MIX_ENV=prod
      - CORS_ORIGINS=http://localhost:5178
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 5178:80
    environment:
      - VITE_API_URL=http://localhost:4005/api
    
volumes:
  db-data: