name: CI/CD Pipeline

on:
  pull_request: 
    branches:
      - master
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '23.0'
        
      - name: Install dependencies
        run: |
          cd backend
          mix deps.get
        
      - name: Run backend tests
        run: |
          cd backend
          mix test
          
