name: Deploy to Google Cloud

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend_piscine:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_piscine:latest
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend_piscine:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_piscine:latest
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and pull Docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend_piscine:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend_piscine:latest
            
            sudo docker compose up -d
            
            sudo docker compose --profile prod up -deploy
            
            docker ps
            echo "Deployment successful"